/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package final_algorithms;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
}
